package com.yehorsk.medicalplatformbackend.medical_records.database.repository

import com.yehorsk.medicalplatformbackend.common.domain.type.MedicalRecordHasBodyPartId
import com.yehorsk.medicalplatformbackend.medical_records.database.entity.MedicalRecordHasBodyPartEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface MedicalRecordHasBodyPartRepository : JpaRepository<MedicalRecordHasBodyPartEntity, MedicalRecordHasBodyPartId>

